
import { City } from './city';

export const CITIES:City[]=[{name:'New York', country_code:'US'},
							{name:'Lagos', country_code:'NG'},
							{name:'Vienna', country_code:'AUS'},
							{name:'Munich', country_code:'GER'},
							{name:'Milan', country_code:'IT'},
							{name:'Ottawa', country_code:'CA'},
							{name:'Vancouver', country_code:'CA'},
							{name:'Minsk', country_code:'PO'},
							{name:'Ibadan', country_code:'NG'},
							{name:'Ankara', country_code:'TUR'},
							{name:'Ondo', country_code:'NG'},
							{name:'Paris', country_code:'FR'},
							{name:'Tokyo', country_code:'JP'},
							{name:'Seoul', country_code:'SK'},
							{name:'Accra', country_code:'GH'},
							{name:'London', country_code:'UK'},
							{name:'Dubai', country_code:'UAE'},
							{name: 'Moscow', country_code:"RU"},
							{name:'Rome', country_code:'IT'},
							{name:'Monrovia', country_code:'LI'},
							{name:'Frankfurt', country_code:'GE'},
							{name:'Johannesburg', country_code:'SA'},
							{name:'Pretoria', country_code:'SA'},
							{name:'Dublin', country_code:'IRE'},
							{name:'Aberdeen', country_code:'WA'},
							{name:'Abidjan', country_code:'IV'},
							{name:'Windhoek', country_code:'NA'},
							{name:'Kigali', country_code:'RW'},
							{name:'Strasbourg', country_code:'FR'},
							{name:'Pyongyang', country_code:'NK'},
							{name:'Brasilia', country_code:'BR'},
							{name:'Caracas', country_code:'VE'},
							{name:"Madrid", country_code:"SP"},
							{name:"Barcelona", country_code:"SP"},
							{name:'Sydney', country_code:'Aus'},
							{name:'Melbourne', country_code:'AUS'},
							{name:'Toronto', country_code:'CA'},
							{name:'California', country_code:'US'},
							{name:'Nantes', country_code:'FR'},
							{name:'Amsterdam', country_code:'NED'},
							{name:'Rotterdam', country_code:'NED'},
							{name:'Zurich', country_code:'SUI'},
							{name:'Jerusalem', country_code:'PS'},
							{name:'Riyadh', country_code:'SA'},
							{name:'Bamako', country_code:'ML'},
							{name:'Lome', country_code:'TO'}


								
								];